const { contextBridge, ipcRenderer } = require('electron');
contextBridge.exposeInMainWorld('api', {
  cloudStatus: () => ipcRenderer.invoke('test:cloud-status'),
  cloudSave: key => ipcRenderer.invoke('test:cloud-save',key),
  cloudModels: () => ipcRenderer.invoke('test:cloud-models'),
  cloudDisconnect: () => ipcRenderer.invoke('test:cloud-disconnect'),
  cloudOpen: async () => ({}),
  pluginsList: () => ipcRenderer.invoke('test:plugins-list'),
  pluginsAdd: config => ipcRenderer.invoke('test:plugins-add', config),
  pluginsToggle: (id, enabled) => ipcRenderer.invoke('test:plugins-toggle', id, enabled),
  pluginsRemove: id => ipcRenderer.invoke('test:plugins-remove', id),
  dataGet: async () => ({ groups: [], chats: [] }), dataSave: async () => ({}),
  settingsGet: async () => ({ appLanguage: process.env.MUSICAL_PREVIEW_LANGUAGE || 'ru', theme: 'dark', teamEnabled: true, downloadedLanguages: ['en', 'ru'] }), settingsSave: async () => ({}),
  ollamaStatus: async () => ({ running: false, models: [] }),
  localStatus: () => ipcRenderer.invoke('test:status'),
  localSetup: () => ipcRenderer.invoke('test:setup'),
  localPull: model => ipcRenderer.invoke('test:pull', model),
  onLocalProgress: () => () => {},
  fluxStatus: async () => ({ ok: true, variants: [] }),
  getProjectsRoot: async () => 'TestProjects',
  ensureProjectFolder: async name => ({ folderName: name, path: 'TestProjects/' + name }),
  projectFileExists: async () => ({ exists: false }),
  writeProjectFile: async () => ({ ok: true }),
  internetSearch: async () => ({ results: [] }),
  onInternetSearchProgress: () => () => {},
  onPullProgress: cb => { ipcRenderer.on('test:pull-progress', (_event, data) => cb(data)); return () => {}; }, onFluxProgress: () => () => {}, onFluxGenerateProgress: () => () => {}
});
